loglevel: DEBUG
routers:
  - sourceName: "local"
    hostColonPort: "127.0.0.1:10110"
views:
  - mapName: "pvd_harbor"
    north: 41.818387
    south: 41.769867
    east: -71.363937
    west: -71.405147
touchFluff: 10.0
